theme: jekyll-theme-minimal
title: Zorba the Buddhah - Mindful Trading
description: Developing and sharing indicators for the Atas.net platform. I am not affiliated with, endorsed by, or working in partnership with the ATAS platform. I am an independent user and enthusiast who has developed these indicators based on my personal experience and extensive use of the ATAS platform.
logo: /assets/image/logo.png
twitter_username: ZorbaTheBuddhah
instagram_username: YourInstagramUsername
email: zorba.the.buddhah@gmail.com

