theme: jekyll-theme-minimal
title: Zorba the Buddhah - Mindful Trading
description: Developing and sharing indicators for the Atas.net platform
logo: /assets/image/logo.png
twitter_username: YourTwitterUsername
instagram_username: YourInstagramUsername

